### PR TITLE
allow other image getters

### LINKED ISSUE #38: why aren't other image getters allowed ?
``` java
if (imageGetter instanceof LocalImageGetter) {
            htmlImageGetter = new HtmlLocalImageGetter(getContext());
        } else if (imageGetter instanceof RemoteImageGetter) {
            htmlImageGetter = new HtmlRemoteImageGetter(this,
                    ((RemoteImageGetter) imageGetter).baseUrl);
        } else {
            Log.e(TAG, "Wrong imageGetter!");
            return;
        }
```
I want to use other fetching libaries while loading images. For example [this](https://gist.github.com/Borales/7531445)

### PR DESCRIPTION
**Pull request by ShikherVerma**
Fixes #38

### CODE REVIEW

**Comment by dschuermann** [comment]
Have you even tried this? Html.ImageGetter does not implement ImageGetter.

**Comment by ShikherVerma** [comment]
Okay understood. Silly mistake. Should I add a new function which can directly accept implementation of `Html.ImageGetter`. Something like  
`setHtmlFromStringWithHtmlImageGetter(Sting html, Html.ImageGetter imageGetter)`  
Refactoring the current `setHtmlFromString` to accept `Html.ImageGetter` will break present code so that is obviously a no go. However `setHtmlFromString` can be refactored to call this after choosing imageGetter, so we can adhere to DRY principle.

**Comment by dschuermann** [comment]
Yup, sounds like a good solution.

**Comment by ShikherVerma** [comment]
fixed in #40

**Pull request closed without merging**
