### PR TITLE
Version 3.8

### PR DESCRIPTION
**Pull request by krzysztofdrobek**

### CODE REVIEW

**Comment by dschuermann** [comment]
? no real code additions have been made.

**Comment by krzysztofdrobek** [comment]
Version 3.7 does not reflect current state of the repo. README states that you can use HtmlFormatter yet class is not available

**Comment by dschuermann** [comment]
Because 3.8 hasn't been released yet. Please when you open a PR please describe here what you like to achieve.
I assume you want a new release?

**Comment by krzysztofdrobek** [comment]
Yes

**Pull request merged**
