### PR TITLE
fix the internet image overlapping and add a new feature

### PR DESCRIPTION
**Pull request by YuanWenHai**
now we can show image as "adjustViewBounds".
that is ,image width will match it's parent and retain it's length-width ratio.(sorry for my bad english o(╯□╰)o )
usage:
text.setHtmlFromString(testRemoteImageHtml,new HtmlTextView.RemoteImageGetter(true));

### CODE REVIEW

**Comment by dschuermann** [comment]
Can you revert the changes to MainActivity? Otherwise it looks good

**Comment by YuanWenHai** [comment]
Sure , my mistake

**Comment by dschuermann** [comment]
Great Thanks

**Comment by dschuermann** [comment]
released in 1.7

**Pull request merged**
